[package]
name = "floem_vger_renderer"
version.workspace = true
edition = "2021"
repository = "https://github.com/lapce/floem"
description = "A native Rust UI library with fine-grained reactivity"
license.workspace = true

[dependencies.floem-vger-rs]
git = "https://github.com/lapce/vger-rs.git"
rev = "643be0713321054a4cb07ae4ad7b440b63b72d72"
version = "0.3.1"
package = "floem-vger"

[dependencies]
image = { workspace = true }
resvg = { workspace = true }
peniko = { workspace = true }
wgpu = { workspace = true }

anyhow = "1.0"
floem_renderer = { path = "../renderer", version = "0.2.0" }
